// <auto-generated />
using System;
using FiapHackatonSimulations.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiapHackatonSimulations.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiapHackatonSimulations.Domain.Entity.SensorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModitificationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Plot")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Plot");

                    b.Property<decimal>("PrecipitationLevel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecipitationLevel");

                    b.Property<decimal>("SoilMoisture")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoilMoisture");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Temperature");

                    b.HasKey("Id");

                    b.ToTable("SensorData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
